import type { Metadata } from "next";
import { AuthProvider } from "./AuthProvider";
import localFont from "next/font/local";
import "./globals.css";
import {updateExpiredPlans} from "./api/SubscriptionCheck/server-task";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "gbMeals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // updateExpiredPlans()
  return (
    <AuthProvider>
    <html lang="en">
      <head>
      <link rel="icon" href="/Resource/gb.png" />
      </head>
      <body
        className={`bg-white ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </AuthProvider>
  );
}
